language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

sudo: required

services:
  - docker

branches:
  only:
  - master

before_install:
  - chmod +x mvnw

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: ./mvnw clean install

after_script:
  - docker build --tag $DOCKER_USERNAME/sentiment-analysis-web-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/sentiment-analysis-web-app
